plugins {
    id 'java'
    id 'io.qameta.allure' version '4.1.0'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.codeborne:selenide:7.9.4'
    testImplementation 'io.qameta.allure:allure-junit5:2.33.0'
    testImplementation 'io.qameta.allure:allure-selenide:2.33.0'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

allure {
    version = "2.33.0"
    adapter {
        frameworks {
            junit5 {
                enabled = true
            }
        }
    }
}


tasks.withType(Test) {
    useJUnitPlatform()
    ignoreFailures = true

    testLogging {
        lifecycle {
            events "started", "skipped", "failed", "standard_error", "standard_out"
            exceptionFormat "short"
        }
    }
}